"""
The 82 AI staff roles of LegacyWorkforce, in 5 departments (from the LegacyWorkforce catalogue).

risk     internal  — drafts for the owner and team only
         customer  — anything a customer sees: every message waits for approval unless the owner lets the department act
         financial — money, quotations, invoices, payments: always waits for approval
conn     connections the role needs to ACT (it can always draft without them)
hero     the ten roles that are fully wired into the hub's own pages; `route` opens that page
produce  what the role's draft contains (handed to the AI)
ask      what the owner tells the role before it starts
"""
DEPARTMENTS = [
    {"id": "marketing", "name": "Marketing", "blurb": "Be found, be trusted, be remembered"},
    {"id": "sales", "name": "Sales", "blurb": "Turn enquiries into confirmed orders"},
    {"id": "support", "name": "Customer support", "blurb": "Answer well, keep customers longer"},
    {"id": "intelligence", "name": "Business intelligence", "blurb": "Decide from evidence, not instinct"},
    {"id": "operations", "name": "Operations & people", "blurb": "Run the business without you in every room"},
]
PER_DEPARTMENT = 6
D = {"M": "marketing", "S": "sales", "C": "support", "I": "intelligence", "O": "operations"}

# (no, dept, name, summary, risk, conn, output, hero_route, produce, ask)
RAW = [
    (1, "M", "Database Researcher", "Inspects your prospect records and finds the gaps worth researching.", "internal", [], "draft", None,
     "a research plan for the prospect list: which records are incomplete, the 10 most promising gaps, where to find each fact, and a fill-in order",
     "Paste or describe your prospect list (who, how many, what you know)"),
    (2, "M", "Lead Enricher", "Adds source-backed company and contact context to your leads.", "internal", [], "draft", None,
     "for each lead given: what to look up, likely decision-maker role, questions to confirm on the first call; never invented facts",
     "List the leads or companies to enrich"),
    (3, "M", "Outreach Writer", "Writes personal introductions using your approved offers.", "customer", ["email"], "message", None,
     "3 short personal introduction messages (WhatsApp and email versions) built only on the approved offers, each with a soft next step",
     "Who are you reaching out to, and why them?"),
    (4, "M", "Telecalling Script Agent", "Prepares call guides with objection branches for your callers.", "internal", [], "draft", None,
     "a calling script: opening line, 3 discovery questions, the pitch in 30 seconds, 5 objections each with a reply branch, and the close",
     "Who will be called, and what is the goal of the call?"),
    (5, "M", "Exhibition Agent", "Builds event packs and consent-aware follow-up for trade shows.", "internal", [], "draft", None,
     "an exhibition pack: stall message, 3 conversation openers, a lead capture checklist with consent line, and day-1/3/7 follow-ups",
     "Which exhibition or event, and what do you want from it?"),
    (6, "M", "WhatsApp Composer", "Adapts messages and next steps for your WhatsApp line.", "customer", ["messaging"], "message", None,
     "the message rewritten for WhatsApp in 3 lengths (one line, short, full), each ending with one clear next step",
     "Paste the message or describe what you want to say"),
    (7, "M", "Content Agent", "A month of posts, scripts and carousels in your voice.", "internal", [], "draft", "/calendar",
     "a month of content: 4 themes, 12 posts with hooks and captions, 4 reel scripts and 2 carousel outlines in the owner's voice",
     "Any theme, offer or festival to focus on this month?"),
    (8, "M", "Video Script Agent", "Scripts, storyboards and captions ready to shoot.", "internal", [], "draft", None,
     "a 45–60 second video: hook (first 3 seconds), script in short lines, 5-shot storyboard for a phone, caption and on-screen text",
     "What should the video be about?"),
    (9, "M", "Website Auditor", "Reviews your website and ranks the fixes that matter.", "internal", [], "draft", None,
     "a ranked list of website fixes: what is missing for a visitor to trust and contact the business, each with the exact change to make",
     "Your website address and anything you already know is wrong"),
    (10, "M", "Lead Magnet Builder", "Creates guides and checklists prospects will trade a number for.", "internal", [], "draft", "/lead-magnet",
     "a lead magnet: title, the problem it solves, 5–7 sections of genuinely useful points, and the call to action",
     "What problem do your best customers have before they buy?"),
    (11, "M", "Google Presence Agent", "Audits your Google Business presence and drafts updates.", "internal", [], "draft", None,
     "a Google Business profile checklist, a 750-character business description, 4 Google posts and 5 photo ideas",
     "Your Google listing name and what you want more of"),
    (12, "M", "Case Study Writer", "Turns verified customer results into case studies.", "internal", [], "draft", None,
     "a case study in Situation–Complication–Question–Answer order, a 2-line testimonial quote to confirm with the customer, and a post version",
     "Which customer, what was the problem and what changed? (facts only)"),
    (13, "M", "Persona Builder", "Builds customer segments from real evidence.", "internal", [], "draft", None,
     "a persona: who they are, needs, desires and problems, what they value, where to find them, words they use, and what makes them buy",
     "Describe your best customers (real examples help)"),
    (14, "M", "Competitor Watcher", "Tracks dated competitor changes worth reacting to.", "internal", [], "draft", None,
     "a competitor watch sheet: what to track for each competitor, how often, and the reactions worth making — no guessed facts",
     "Name your main competitors and what you've noticed"),
    (15, "M", "Pricing Research Agent", "Compares like-for-like market prices and terms.", "internal", [], "draft", None,
     "a like-for-like price comparison plan: what to compare, where to get each price, and how to read the result against your floor",
     "Which product or service, and who do customers compare you with?"),
    (16, "M", "Brand Voice Guardian", "Checks wording, tone and claims against your brand rules.", "internal", [], "draft", None,
     "the text checked line by line: tone fixes, claims that need proof, words to avoid, and the corrected version",
     "Paste the text to check"),
    (17, "M", "Testimonial Harvester", "Finds attributable praise and asks for publication consent.", "customer", ["email"], "message", None,
     "a consent request message for each happy customer, with the exact quote they would approve and a thank-you",
     "Which customers said something good, and what did they say?"),
    (18, "M", "PR & Awards Agent", "Finds award and press opportunities and drafts submissions.", "internal", [], "draft", None,
     "a list of the kinds of awards and press angles that fit, and one submission draft built only on real facts",
     "What achievement or story do you want known?"),
    (19, "S", "Inquiry Qualifier", "Answers new enquiries from your approved offers and checks fit.", "customer", ["messaging"], "reply", "/chats",
     "a qualifying reply plan: the 4 questions that tell a good-fit lead from a poor one, and the reply for each answer",
     "What makes a lead a good fit for you?"),
    (20, "S", "Lead Router", "Routes leads to the right person using your rules.", "internal", [], "draft", None,
     "routing rules: which leads go to whom (by area, product, size), the hand-over message, and what happens if nobody picks up",
     "Who is on your sales team and what does each handle?"),
    (21, "S", "Meeting Setter", "Finds real free slots and books the meeting.", "customer", ["calendar"], "calendar", None,
     "meeting booking messages: the ask, 3 slot options, confirmation, reminder the day before, and a reschedule reply",
     "What kind of meeting, how long, and when are you usually free?"),
    (22, "S", "Briefing Writer", "A one-page brief before every confirmed meeting.", "internal", [], "draft", None,
     "a one-page meeting brief: who they are, what they likely need, questions to ask, offers to show, and objections to expect",
     "Who are you meeting and what do you know about them?"),
    (23, "S", "Pitch Designer", "Proposals and presentations shaped to the customer's need.", "internal", [], "draft", None,
     "a proposal outline: the customer's situation in their words, the recommended offer, what's included, timeline, and next step",
     "Who is the proposal for and what do they need?"),
    (24, "S", "Quotation Officer", "Turns a voice note or brief into today's quotation, tax worked out.", "financial", [], "quote", "/quotes",
     "quotation lines with item, quantity and the owner's price; totals and GST are worked out by the hub", "What does the customer want?"),
    (25, "S", "Boundary Price Guard", "Checks every price and concession against your floor.", "internal", [], "draft", None,
     "a check of the proposed price and concessions against the floor the owner gives, and what to offer instead of a discount",
     "What price or discount is being asked for, and what is your floor?"),
    (26, "S", "Negotiation Advisor", "Suggests the next move — add value instead of cutting price.", "internal", [], "draft", None,
     "3 negotiation moves that add value instead of cutting price, the words to say for each, and when to walk away",
     "Where is the deal stuck and what has the customer said?"),
    (27, "S", "Order Confirmation", "Records explicit acceptance. Never assumes payment.", "customer", ["messaging"], "message", None,
     "an order confirmation message listing exactly what was agreed, the dates, and how payment works — asking the customer to confirm",
     "What did the customer agree to?"),
    (28, "S", "Quote Follow-Up", "Follows up open quotations — politely, on schedule, with stop rules.", "customer", ["messaging"], "message", "/agents",
     "follow-up messages for day 2, 5 and 10 after a quotation, each adding a reason to reply, and the stop rule", "Which quotation is open?"),
    (29, "S", "Ghost Resurrector", "Re-engages leads that went quiet, with a reason to reply.", "customer", ["messaging"], "message", None,
     "3 re-engagement messages for quiet leads, each with a genuine reason to reply and an easy yes/no question",
     "Which leads went quiet, and what were they interested in?"),
    (30, "S", "Deal Manager", "Keeps every deal's stage, commitments and next step honest.", "internal", [], "draft", None,
     "a deal review: each open deal's real stage on the Football Field, what was promised, the next step and its date",
     "List your open deals and where you think each stands"),
    (31, "S", "Lost Deal Analyst", "Finds the patterns in deals you lost.", "internal", [], "draft", None,
     "patterns in the lost deals: at which stage they were lost, the likely reasons, and 3 changes to try",
     "List deals you lost and what you were told"),
    (32, "S", "Referral Request", "Asks happy customers for referrals at the right moment.", "customer", ["messaging"], "message", None,
     "a 3-step referral conversation (share the vision → ask for a testimonial → ask for a referral) with WhatsApp versions",
     "Which happy customers, and what kind of referral do you want?"),
    (33, "S", "Referral Program", "Tracks who referred whom and who earned a reward.", "internal", [], "draft", None,
     "a referral program: the reward for both sides, how referrals are tracked, the launch message, and a caution check for B2B",
     "What can you offer as a reward, and to whom?"),
    (34, "S", "Tender Pursuit Agent", "Assesses tender fit and builds the pursuit pack.", "internal", [], "draft", None,
     "a tender fit check (must-haves, risks, go/no-go) and the pursuit pack checklist",
     "Paste the tender summary or link details"),
    (35, "S", "Sales Coach", "Reviews sales conversations and coaches specific fixes.", "internal", [], "draft", "/gym",
     "a scored review of the conversation (listening, questions, value before price, handling objections, close) with 3 specific fixes",
     "Paste a sales conversation or call notes"),
    (36, "C", "Inquiry Concierge", "Answers support questions from your policies; opens tickets when needed.", "customer", ["messaging"], "reply", "/chats",
     "reply drafts for the common support questions, built only from the policies and FAQs given, and when to hand over to a person",
     "What do customers ask most after they buy?"),
    (37, "C", "Multilingual Reply", "Rewrites replies in the customer's language, facts unchanged.", "internal", [], "draft", None,
     "the reply in the requested languages with the facts unchanged, and a note of any word that doesn't translate well",
     "Paste the reply and the language(s) you need"),
    (38, "C", "Ticket Router", "Classifies issues and opens tickets in your support desk.", "internal", [], "draft", None,
     "an issue classification: category, urgency, who should own it, and the first reply to the customer",
     "Describe the customer's issue"),
    (39, "C", "Ticket Escalator", "Applies urgency rules and escalates to the right owner.", "internal", [], "draft", None,
     "escalation rules: what is urgent, who gets it, by when, and the escalation message",
     "What kinds of issues come up, and who handles them?"),
    (40, "C", "SLA Monitor", "Watches response deadlines and warns before they slip.", "internal", [], "draft", None,
     "response-time promises for each kind of request and the warning messages before they slip",
     "How quickly do you promise to respond today?"),
    (41, "C", "Warranty Tracker", "Matches orders to your warranty terms.", "internal", [], "draft", None,
     "a warranty check for the order: what's covered, until when, what to ask the customer, and the reply",
     "Your warranty terms and the order in question"),
    (42, "C", "Refund Advisor", "Explains policy and prepares a refund decision for you.", "financial", [], "draft", None,
     "the refund decision prepared for the owner: what the policy says, the options, and the customer message for each — the owner decides",
     "Your refund policy and the customer's request"),
    (43, "C", "Review & Rating", "Asks satisfied customers for a review after service.", "customer", ["messaging"], "message", "/agents",
     "review request messages for after service, with the review link placeholder and a thank-you", "Which customers were happy recently?"),
    (44, "C", "Review Moderator", "Drafts calm, on-brand replies to public reviews.", "internal", [], "draft", None,
     "a calm public reply for each review (thank, address, invite offline for problems) — never arguing",
     "Paste the reviews you need to reply to"),
    (45, "C", "Silent Customer Detector", "Spots customers who went quiet and suggests a check-in.", "internal", [], "draft", "/customers",
     "a list of signs a customer is going quiet and a check-in message for each kind",
     "Who used to buy and hasn't recently?"),
    (46, "C", "Reorder Reminder", "Reminds customers to reorder based on purchase history.", "customer", ["messaging"], "message", "/customers",
     "reorder reminder messages timed to the usual reorder cycle, with an easy way to reply", "What do customers reorder, and how often?"),
    (47, "C", "Client Health Monitor", "Flags accounts at risk before they leave.", "internal", [], "draft", None,
     "an account health check: the warning signs to watch, the health score rules, and what to do at each level",
     "Which accounts matter most, and what do you know about each?"),
    (48, "C", "Customer Spotlight", "Turns customer stories into content, with consent.", "internal", [], "draft", None,
     "a customer spotlight post, a consent request message, and 3 follow-up post ideas",
     "Which customer, and what is their story?"),
    (49, "C", "Anniversary Agent", "Remembers customer milestones and sends a warm note.", "customer", ["messaging"], "message", "/customers",
     "warm notes for customer milestones (purchase anniversary, birthday, business anniversary)", "Which milestones do you know?"),
    (50, "C", "Community Manager", "Handles community questions and spots buying intent.", "internal", [], "draft", None,
     "a community plan: purpose, platform, monthly content calendar, engagement prompts, and how to spot buying intent",
     "Who would be in your community, and why would they join?"),
    (51, "I", "Sales Pattern Analyst", "Finds the products, months and customers driving revenue.", "internal", [], "draft", None,
     "patterns in the sales data given: best products, months and customers, with what to do about each — only from the numbers given",
     "Paste your sales summary (product, month, customer, amount)"),
    (52, "I", "Customer Profitability", "Sorts every customer by return on effort.", "internal", [], "draft", "/portfolio",
     "customers sorted by return on effort (Amazing, Breadwinning, Convenience, Dangerous) with the focus rule for each",
     "List customers with yearly value, margin and effort"),
    (53, "I", "Voice-of-Customer Miner", "Pulls real needs and objections out of conversations.", "internal", [], "draft", None,
     "the needs, desires, problems and objections in the conversations given, with the exact phrases customers use",
     "Paste customer messages, reviews or call notes"),
    (54, "I", "Market Sizing Agent", "Estimates your market with every assumption visible.", "internal", [], "draft", None,
     "a market estimate built step by step, every assumption written out so the owner can change it",
     "Which market and area?"),
    (55, "I", "Meeting Insight Extractor", "Extracts decisions and commitments from meetings.", "internal", [], "draft", "/meetings",
     "decisions, commitments (who, what, by when) and open questions from the meeting notes", "Paste the meeting notes"),
    (56, "I", "Magic Number Tracker", "Calculates your key business numbers from definitions you approve.", "internal", [], "draft", "/magic",
     "the definitions of the key numbers to track weekly and how to read them", "What target are you working towards?"),
    (57, "I", "Cash Flow Forecaster", "Models next month's cash from receivables and payables.", "internal", ["accounting"], "draft", None,
     "a cash flow view for next month from the receivables and payables given, with the weeks that need attention",
     "What money is coming in and going out next month?"),
    (58, "I", "Sales Forecaster", "Forecasts from your real pipeline, with uncertainty shown.", "internal", [], "draft", None,
     "a forecast from the pipeline given: likely, best and worst case, and the deals that decide it",
     "List open deals with value and stage"),
    (59, "I", "Pricing Strategist", "Recommends pricing options without touching approved prices.", "internal", [], "draft", None,
     "3 pricing options (with the reasoning and risks) for the owner to decide — approved prices are never changed",
     "Which product, today's price, and what you want to achieve"),
    (60, "I", "Campaign Planner", "Audiences, assets, budget and measurement in one plan.", "internal", [], "draft", "/campaigns",
     "a campaign plan: audience, message, assets, channels, budget split, timeline and what to measure", "What's the campaign for?"),
    (61, "I", "Competitor Intel", "Explains what competitor moves mean for you.", "internal", [], "draft", None,
     "what the competitor move means for the business, the options, and the recommended response",
     "What did the competitor do?"),
    (62, "I", "Trend Scout", "Spots relevant signals and proposes small experiments.", "internal", [], "draft", None,
     "3 trends worth testing for this business and a small 2-week experiment for each",
     "What's changing in your industry or among your customers?"),
    (63, "I", "Tender Finder", "Researches procurement opportunities and deadlines.", "internal", [], "draft", None,
     "where to look for relevant tenders, the search terms to use, and a weekly tender review routine",
     "What kind of government or corporate work do you want?"),
    (64, "I", "Expansion Analyst", "Compares new locations or channels with explicit assumptions.", "internal", [], "draft", None,
     "a comparison of the expansion options with every assumption visible, the risks, and a small first step",
     "Which locations or channels are you considering?"),
    (65, "O", "Morning Manager", "Your daily briefing — priorities, money owed, what needs you.", "internal", [], "briefing", "/agents",
     "a morning briefing: today's 3 priorities, what needs the owner, and what can wait", "Anything special about today?"),
    (66, "O", "Team's Second Brain", "Answers your team's questions from approved sources.", "internal", [], "draft", "/company-brain",
     "answers to the team's question built only from the approved SOPs and documents, saying so when the answer isn't there",
     "What does your team keep asking?"),
    (67, "O", "SOP Writer", "Writes procedures with owners, steps and exceptions.", "internal", [], "draft", "/sops",
     "an SOP with purpose, owner, steps in order, checklist and exceptions", "Which process?"),
    (68, "O", "Task Chaser", "Follows up commitments on your timing rules.", "internal", [], "draft", "/tasks",
     "follow-up messages for open commitments: a nudge, a firmer reminder, and an escalation", "Which tasks or commitments are slipping?"),
    (69, "O", "Meeting Minutes", "Turns notes or a transcript into minutes and action items.", "internal", [], "draft", "/meetings",
     "minutes: decisions, action items with owner and date, and open questions", "Paste the notes or transcript"),
    (70, "O", "Dispatch Coordinator", "Coordinates shipments from your dispatch records.", "internal", [], "draft", None,
     "a dispatch plan for the orders given: sequence, what to confirm with each customer, and the update messages",
     "List the orders to dispatch and any constraints"),
    (71, "O", "Recovery Officer", "Chases what is owed — politely, then firmly. You approve every message.", "financial", ["accounting"], "recovery", "/money",
     "a reminder ladder (polite, firm, final) for the amount owed — every message waits for the owner", "Who owes what, since when?"),
    (72, "O", "Invoice Agent", "Prepares tax-correct invoices from approved order data.", "financial", [], "invoice", "/quotes",
     "invoice lines from the approved order; totals and GST are worked out by the hub", "Which order?"),
    (73, "O", "Compliance Calendar", "Tracks filings and renewals with a named owner for each.", "internal", [], "draft", None,
     "a compliance calendar: each filing or renewal, its usual timing, the owner, and the reminder schedule — to confirm with the CA",
     "Which registrations and licences does your business have?"),
    (74, "O", "Contract Reviewer", "Highlights clauses for a responsible person to review.", "internal", [], "draft", None,
     "the clauses that need a responsible person's attention (payment, liability, termination, penalties) and questions to ask — not legal advice",
     "Paste the contract or the clauses"),
    (75, "O", "Stock Alert Agent", "Watches stock thresholds and proposes reorders.", "internal", [], "draft", None,
     "reorder levels for each item from the usage given and the reorder messages to suppliers",
     "List items, current stock and monthly usage"),
    (76, "O", "Reconciler", "Matches transactions and explains differences.", "internal", ["accounting"], "draft", None,
     "a reconciliation of the two lists given: matched items, differences, and the likely reason for each",
     "Paste the two lists to match"),
    (77, "O", "Hiring Assistant", "Structured, job-related screening. People decide.", "internal", [], "draft", "/hiring",
     "a structured screening: must-haves, interview questions with what a good answer shows, and a scorecard — people decide", "Which role?"),
    (78, "O", "Onboarding Trainer", "Role-specific learning plans from your procedures.", "internal", [], "draft", None,
     "a 30-day onboarding plan for the role: week by week, which SOPs to learn, who to shadow, and checks",
     "Which role, and who is joining?"),
    (79, "O", "Scorecard Agent", "Reports team measures with the evidence behind them.", "internal", [], "draft", None,
     "a team scorecard: the measures for each role, how to collect them, and the weekly review format",
     "Which roles do you want to measure?"),
    (80, "O", "Training Drill", "Role-plays that find the gaps in your team's skills.", "internal", [], "draft", "/gym",
     "3 role-play drills for the skill given, with the customer's lines, what good looks like, and how to score", "Which skill?"),
    (81, "O", "Recognition Agent", "Recognises verified milestones, privately or publicly.", "internal", [], "draft", None,
     "recognition messages for the milestones given — a private note and a team announcement", "Who achieved what?"),
    (82, "O", "Focus Guardian", "Protects your calendar for the work only you can do.", "internal", ["calendar"], "draft", None,
     "a weekly calendar plan that protects the owner's focus time, what to delegate, and how to say no",
     "What does your week look like now?"),
]

ROLES = []
for no, dept, name, summary, risk, conn, output, route, produce, ask in RAW:
    ROLES.append({"id": no, "key": f"role:{no}", "department": D[dept], "name": name, "summary": summary, "risk": risk,
                  "conn": conn, "output": output, "route": route, "hero": route is not None and no in (7, 19, 21, 24, 28, 36, 65, 69, 71, 72),
                  "produce": produce, "ask": ask,
                  "minutes": 25 if output == "draft" else 8 if output in ("message", "reply") else 20})
BY_ID = {r["id"]: r for r in ROLES}
HERO_IDS = [7, 19, 21, 24, 28, 36, 65, 69, 71, 72]
for _r in ROLES:
    _r["hero"] = _r["id"] in HERO_IDS
assert len(ROLES) == 82


def role(no) -> dict | None:
    try:
        return BY_ID.get(int(no))
    except (TypeError, ValueError):
        return None


def department_of(no) -> str | None:
    r = role(no)
    return r["department"] if r else None
